### PR TITLE
Use `openssl_3_0` and `niv update` all deps

### LINKED ISSUE #48: Ubuntu 22.04: libssl.so.1.1: cannot open shared object file
So I tried upgrading from ubuntu 20 to ubuntu 22 but it seems that on 22 they're using the new improved openssl3. 

If I try to use vessel I get this: `vessel: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Can vessel start using openssl3 or is that a dependency out of your hands? 

Related: 

https://stackoverflow.com/questions/72133316/ubuntu-22-04-libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-di

### PR DESCRIPTION
**Pull request by ggreif**
It appears that recent Ubuntu distros don't include `openssl-1.1.1` by default any more (fixes #48), this PR adopts 3.0.

v3.0 of `openssl` has been released on 8 Sept 2021, so it should be widespread enough in recent distributions.

Also bumps:
- `nix` deps (e.g. `release-22.05`)
- `cargo` deps
- some GH actions

### CODE REVIEW

**Comment by ggreif** [comment]
@kritzcreek feel free to ignore the review request!

**Comment by ggreif** [comment]
@kentosugama I'd be glad to walk you through all of these commits explaining what they do and what they are good for.

**Review by matthewhammer — APPROVED** [review]
LGTM.

**Comment by ggreif** [comment]
I an not the owner of the repos, but I have done 2 releases, and can
comment on the commits in this PR (only) :-)

**Pull request merged**
