### PR TITLE
bugfix: update cargoSha256 to restore CI

### PR DESCRIPTION
**Pull request by crusso**

### CODE REVIEW

**Comment by ByronBecker** [comment]
@crusso @kritzcreek Thanks for fixing this - can we tag this as `v0.6.3` and trigger the release workflow?

(so it can be picked up by GitHub CI ,i.e. the `https://github.com/dfinity/vessel/releases/download/v0.6.3/vessel-linux64` link in `ci.yml` and `release.yml`)

**Comment by ggreif** [comment]
@ByronBecker I have pushed #44. Let's let this soak a bit and then I'll merge and tag.

**Comment by ggreif** [comment]
@ByronBecker https://github.com/dfinity/vessel/releases/tag/v0.6.3 gets hopefully released in short order now.

**Comment by ByronBecker** [comment]
@ggreif Thanks for keeping me posted!

**Comment by ggreif** [comment]
@ByronBecker it is released now, grab it while hot!

**Pull request merged**
